### ISSUE TITLE
tests/integration/restore is too slow on Windows

### ISSUE THREAD

**Issue by taro-m** [KiiPlatform/gateway-agent#161]
I got this output

```
$ go test
Running Suite: Integration under Restore Mode Suite
===================================================
Random Seed: 1458839873
Will run 1 of 1 specs

Press CTRL-C to terminate
IoTGW 02:17:53 server starts to listen: 127.0.0.1:1884
+ [SLOW TEST:14.521 seconds]
Restore Gateway
D:/home/koron/gowork/src/github.com/KiiPlatform/gateway-agent/tests/integration/restore/restore-gateway_test.go:162
  Should Success
  D:/home/koron/gowork/src/github.com/KiiPlatform/gateway-agent/tests/integration/restore/restore-gateway_test.go:160
------------------------------

Ran 1 of 1 Specs in 15.558 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 0 Skipped PASS
ok      github.com/KiiPlatform/gateway-agent/tests/integration/restore  15.611s
```

**Comment by taro-m** [comment]
Circle-CI を見ると、SLOW TEST がもっと多く記録されている。

なにか手がないか、検討したほうが良いかもしれない。
ginkgoのオプションでしきい値を変更するとか。

**Comment by yongpingchen** [comment]
I know why. Since each time after test, do not clear the end-node, so the number of end-node is becoming more and more. May be it is better to clear end-node each time after test.

**Comment by taro-m** [comment]
It is OK that there are slow tests.
It would be enough that extend more time to detect slow for those tests.

**Comment by yongpingchen** [comment]
I deleted all end-node from master app and end-node app. Need 12.23 seconds on circleCI(https://circleci.com/gh/KiiPlatform/gateway-agent/568). Previously 27.57 seconds(around 55 end-node on master app and 55 end-nodes on endnode app)(https://circleci.com/gh/KiiPlatform/gateway-agent/560)

**Comment by yongpingchen** [comment]
ginkgo allow you to do this 
`go test -ginkgo.slowSpecThreshold=10 #10 is 10 seconds `

**Comment by taro-m** [comment]
added `-ginkgo.slowSpecThreshold` in #212
