### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by nfukuzaki** [KiiPlatform/gateway-agent#192]
gatewayのappサンプルを作成していて気づいた点をメモ書きしておきます。

1. 同じLAN内のGatewayを探す(IPを検出)仕組みが欲しい
2. PendingNodeの一覧ではなくOnboardedNodeの一覧取得のAPIが欲しい
3. APPを跨いでGateway経由でCommandなどを投げれるようにしたい

**Comment by yongpingchen** [comment]
For 3/3, the commands among different apps need support of kii cloud, it is concerned by gateway.
