### ISSUE TITLE
Agenda on Mid. Jan 2016

### ISSUE THREAD

**Issue by taro-m** [KiiPlatform/gateway-agent#69]
* [ ] Current Issues
  * [ ] Configuration for local servers (listen address and ports)
  * [ ] Depending surgemq library/process
  * [ ] No restore oprations
* [x] Publish first version
  * [x] Documentation (including samples easy to start)
  * [ ] Test on device (Raspberry Pi or edison)
* [ ] Next version planning
  * [ ] Replace MQTT library with go-mqtt
    * [ ] go-mqtt: need tests
    * [ ] go-mqtt: rewrite/arrange server adapter
  * [ ] Implment resotre operations
  * [ ] HTTPS/MQTTS support
  * [ ] converter reference
  * [ ] anything other?

**Comment by satoshikumano** [comment]
moved to
https://docs.google.com/document/d/16s2lJd6gqP8XDjgBsmrzKDhLwcUQD7zZFgxZZxy3LB8/edit#
