### ISSUE TITLE
how transition state when restore gateway app

### ISSUE THREAD

**Issue by taro-m** [KiiPlatform/gateway-agent#91]
How about this?

1.  make gateway app, onboarding
2.  make all endnode apps, onboarding
3.  restore gateway app data
4.  restore each endnode apps data
5.  make restored endnode apps, done
6.  remove state for endnode apps which failed to restore, or just record error?
7.  make gateway app, done

**Comment by yongpingchen** [comment]
Will check `mode` of gateway first, if gateway is in `restore mode`, then the operation will be ignored. 
After all the gateway finished restoring, the mode of gateway will be changed to `normal mode`
